[package]
name = "libpep"
version = "0.4.0"
edition = "2021"
authors = ["Bernard van Gastel <bvgastel@bitpowder.com>", "Job Doesburg <job@jobdoesburg.nl>"]
homepage = "https://www.bitpowder.com/libs/libpep-rust/"
repository = "https://gitlab.com/bitpowder/indigo-ng"
license = "Apache-2.0"
keywords = ["crypto", "pep", "pseudonimization"]
categories = ["command-line-interface"]
description = "implementation of PEP primitives, offering pseudonimization and encryption interfaces"
readme = "README.md"

[features]
default = ["build-binary"]
build-binary = ["buildinfy","commandy","commandy_macros"]

[dependencies]
wasm-bindgen = "0.2"
curve25519-dalek = { version = "4", features = ["rand_core"] }
rand = { version = "^0.8", features = ["std"] }
rand_core = { version = "^0.6", features = ["std"] }
sha2 = "0.10.5"
buildinfy = { version = "^0.1", optional = true }
commandy = { version = "^0.2", optional = true }
commandy_macros = { version = "^0.2", optional = true }
hex = "0.4.3"

# testing
time = "0.3.36"
base64 = "0.22.1"

# wasm
wasm-bindgen-test = "0.3"
getrandom = { version = "^0.2", features = ["js"] }
log = "0.4.22"

[lib]
crate-type = ["cdylib", "rlib", "wasm"]
