[package]
name = "libpep"
version = "0.4.0"
edition = "2021"
authors = ["Bernard van Gastel <bvgastel@bitpowder.com>", "Job Doesburg <job@jobdoesburg.nl>"]
homepage = "https://www.bitpowder.com/libs/libpep-rust/"
repository = "https://gitlab.com/bitpowder/indigo-ng"
license = "Apache-2.0"
keywords = ["crypto", "pep", "pseudonimization"]
categories = ["command-line-interface"]
description = "implementation of PEP primitives, offering pseudonimization and encryption interfaces"
readme = "README.md"

[features]
default = ["build-binary"]
build-binary = ["buildinfy","commandy","commandy_macros"]

[dependencies]
curve25519-dalek = "3"
rand = { version = "0.7", features = ["std"] }
rand_core = { version = "0.5", features = ["std"] }
sha2 = "0.10.5"
buildinfy = { version = "^0.1", optional = true }
commandy = { version = "^0.2", optional = true }
commandy_macros = { version = "^0.2", optional = true }
hex = "0.4.3"
ureq = "2.9.6"
libaes = "0.7.0"
