[package]
name = "libpep"
version = "0.4.0"
edition = "2021"
authors = ["Bernard van Gastel <bvgastel@bitpowder.com>", "Job Doesburg <job@jobdoesburg.nl>"]
homepage = "https://www.bitpowder.com/libs/libpep-rust/"
repository = "https://gitlab.com/bitpowder/indigo-ng"
license = "Apache-2.0"
keywords = ["crypto", "pep", "pseudonimization"]
categories = ["command-line-interface"]
description = "implementation of PEP primitives, offering pseudonimization and encryption interfaces"
readme = "README.md"

[features]
default = ["build-binary"]
build-binary = ["buildinfy","commandy","commandy_macros","hyper","hyper-util","rustls-webpki","tokio-rustls","rustls-native-certs","rustls-pemfile"]

[dependencies]
curve25519-dalek = "3"
rand = { version = "0.7", features = ["std"] }
rand_core = { version = "0.5", features = ["std"] }
sha2 = "0.10.5"
buildinfy = { version = "^0.1", optional = true }
commandy = { version = "^0.2", optional = true }
commandy_macros = { version = "^0.2", optional = true }
hex = "0.4.3"
ureq = { version = "2.9.6", features = ["tls"] }
libaes = "0.7.0"

# HTTP + TLS benchmark
hyper = { version = "^1.0", features = ["client","http1","http2","server"], optional = true }
hyper-util = { version = "^0.1", features = ["client-legacy","server-auto","server","http1","http2","tokio"], optional = true }
http-body-util = { version = "^0.1" }
rustls-webpki = { version = "^0.102", optional = true }
tokio-rustls = { version = "^0.25", optional = true }
rustls-native-certs = { version = "^0.7", optional = true }
rustls-pemfile = { version = "^2.0", optional = true }

# async runtime
tokio = { version = "^1", features = ["signal","rt-multi-thread","macros","io-util","parking_lot","time","test-util"]  }
tokio-util = { version = "^0.7", features = ["codec"] }
tokio-stream = { version = "^0.1" }
bytes = { version = "^1" }
futures = { version = "^0.3" }

# testing
crashy = { version = "^0.2", features = ["trace"] }
time = "0.3.36"
