name: Build and Test

on:
  push:
    branches:
      - '**'
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: 
          - ""
          - "elgamal2"
          - "legacy-pep-repo-compatible"
          - "elgamal2,legacy-pep-repo-compatible"

    name: cargo test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --features "${{ matrix.features }}"

  build-wasm:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        target: [ "web", "nodejs" ]
        features: [ "", "elgamal2" ]

    name: wasm-pack build
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install wasm-pack
      - run: wasm-pack build --target ${{ matrix.target }} --features "wasm,${{ matrix.features }}"
      - uses: actions/upload-artifact@v4
        with:
          name: libpep-wasm-${{ matrix.target }}-${{ matrix.features }}
          path: pkg/
