name: Build WASM

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        target: [ "web", "nodejs" ]
        features: [ "", "elgamal2" ]

    name: wasm-pack build
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install wasm-pack
      - run: wasm-pack build --target ${{ matrix.target }} --features "wasm,${{ matrix.features }}"
      - uses: actions/upload-artifact@v4
        with:
          name: libpep-wasm-${{ matrix.target }}-${{ matrix.features }}
          path: pkg/
