name: Publish new version

on:
  release:
    types: [created]


jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    name: Build and publish to npm
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: cargo install wasm-pack
      - run: wasm-pack build --release --target nodejs --features wasm
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-crate:
    runs-on: ubuntu-latest

    name: Build and publish to crates.io
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
