name: Publish new version

on:
  release:
    types: [created]


jobs:
  publish-npm:
    runs-on: ubuntu-latest

    name: wasm-pack build
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-node@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: cargo install wasm-pack
      - run: wasm-pack build --release --target nodejs --features wasm
      - run: wasm-pack publish