name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: 
          - ""
          - "elgamal2"
          - "legacy-pep-repo-compatible"
          - "elgamal2,legacy-pep-repo-compatible"

    name: cargo test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --features "${{ matrix.features }}"

